# Generated by Django 4.0.2 on 2022-03-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_remove_jobseeker_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
