# Generated by Django 4.0.2 on 2022-03-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
