# Generated by Django 4.0.2 on 2022-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobseeker_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='gender',
        ),
    ]
